id = "macos-liquid-glass-theme"
name = "MacOS Liquid Glass"
version = "0.0.1"
schema_version = 1
authors = ["Adonai Tewolde"]
description = "A dark liquid glass theme for Zed inspired by Apple design."
repository = "https://github.com/adotew/macos-liquid-glass-theme"
